//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.IB_Laboratornaya_Rabota
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Опр потр тз.
    /// </summary>
    // *** Start programmer edit section *** (ОпрПотрТз CustomAttributes)

    // *** End programmer edit section *** (ОпрПотрТз CustomAttributes)
    [AutoAltered()]
    [Caption("Опр потр тз")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОпрПотрТзE", new string[] {
            "Дата as \'Дата создания\'",
            "СпрСотр as \'Фио сотрудника\'",
            "СпрСотр.Фио as \'Фио сотрудника\'",
            "РабОтдел as \'Рабочий отдел\'",
            "РабОтдел.Наименование as \'Рабочий отдел\'"})]
    [AssociatedDetailViewAttribute("ОпрПотрТзE", "ТчОпрПотрТз", "ТчОпрПотрТзE", true, "", "Табличная часть определение потребностей технической защиты", true, new string[] {
            ""})]
    [View("ОпрПотрТзL", new string[] {
            "Дата as \'Дата сотрудник\'",
            "СпрСотр.Фио as \'Фио сотрудника\'",
            "РабОтдел.Наименование as \'Рабочий отдел\'"})]
    public class ОпрПотрТз : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.IB_Laboratornaya_Rabota.СпрСотр fСпрСотр;
        
        private IIS.IB_Laboratornaya_Rabota.РабОтдел fРабОтдел;
        
        private IIS.IB_Laboratornaya_Rabota.DetailArrayOfТчОпрПотрТз fТчОпрПотрТз;
        
        // *** Start programmer edit section *** (ОпрПотрТз CustomMembers)

        // *** End programmer edit section *** (ОпрПотрТз CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ОпрПотрТз.Дата CustomAttributes)

        // *** End programmer edit section *** (ОпрПотрТз.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ОпрПотрТз.Дата Get start)

                // *** End programmer edit section *** (ОпрПотрТз.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ОпрПотрТз.Дата Get end)

                // *** End programmer edit section *** (ОпрПотрТз.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОпрПотрТз.Дата Set start)

                // *** End programmer edit section *** (ОпрПотрТз.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ОпрПотрТз.Дата Set end)

                // *** End programmer edit section *** (ОпрПотрТз.Дата Set end)
            }
        }
        
        /// <summary>
        /// Опр потр тз.
        /// </summary>
        // *** Start programmer edit section *** (ОпрПотрТз.РабОтдел CustomAttributes)

        // *** End programmer edit section *** (ОпрПотрТз.РабОтдел CustomAttributes)
        [PropertyStorage(new string[] {
                "РабОтдел"})]
        [NotNull()]
        public virtual IIS.IB_Laboratornaya_Rabota.РабОтдел РабОтдел
        {
            get
            {
                // *** Start programmer edit section *** (ОпрПотрТз.РабОтдел Get start)

                // *** End programmer edit section *** (ОпрПотрТз.РабОтдел Get start)
                IIS.IB_Laboratornaya_Rabota.РабОтдел result = this.fРабОтдел;
                // *** Start programmer edit section *** (ОпрПотрТз.РабОтдел Get end)

                // *** End programmer edit section *** (ОпрПотрТз.РабОтдел Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОпрПотрТз.РабОтдел Set start)

                // *** End programmer edit section *** (ОпрПотрТз.РабОтдел Set start)
                this.fРабОтдел = value;
                // *** Start programmer edit section *** (ОпрПотрТз.РабОтдел Set end)

                // *** End programmer edit section *** (ОпрПотрТз.РабОтдел Set end)
            }
        }
        
        /// <summary>
        /// Опр потр тз.
        /// </summary>
        // *** Start programmer edit section *** (ОпрПотрТз.СпрСотр CustomAttributes)

        // *** End programmer edit section *** (ОпрПотрТз.СпрСотр CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрСотр"})]
        [NotNull()]
        public virtual IIS.IB_Laboratornaya_Rabota.СпрСотр СпрСотр
        {
            get
            {
                // *** Start programmer edit section *** (ОпрПотрТз.СпрСотр Get start)

                // *** End programmer edit section *** (ОпрПотрТз.СпрСотр Get start)
                IIS.IB_Laboratornaya_Rabota.СпрСотр result = this.fСпрСотр;
                // *** Start programmer edit section *** (ОпрПотрТз.СпрСотр Get end)

                // *** End programmer edit section *** (ОпрПотрТз.СпрСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОпрПотрТз.СпрСотр Set start)

                // *** End programmer edit section *** (ОпрПотрТз.СпрСотр Set start)
                this.fСпрСотр = value;
                // *** Start programmer edit section *** (ОпрПотрТз.СпрСотр Set end)

                // *** End programmer edit section *** (ОпрПотрТз.СпрСотр Set end)
            }
        }
        
        /// <summary>
        /// Опр потр тз.
        /// </summary>
        // *** Start programmer edit section *** (ОпрПотрТз.ТчОпрПотрТз CustomAttributes)

        // *** End programmer edit section *** (ОпрПотрТз.ТчОпрПотрТз CustomAttributes)
        public virtual IIS.IB_Laboratornaya_Rabota.DetailArrayOfТчОпрПотрТз ТчОпрПотрТз
        {
            get
            {
                // *** Start programmer edit section *** (ОпрПотрТз.ТчОпрПотрТз Get start)

                // *** End programmer edit section *** (ОпрПотрТз.ТчОпрПотрТз Get start)
                if ((this.fТчОпрПотрТз == null))
                {
                    this.fТчОпрПотрТз = new IIS.IB_Laboratornaya_Rabota.DetailArrayOfТчОпрПотрТз(this);
                }
                IIS.IB_Laboratornaya_Rabota.DetailArrayOfТчОпрПотрТз result = this.fТчОпрПотрТз;
                // *** Start programmer edit section *** (ОпрПотрТз.ТчОпрПотрТз Get end)

                // *** End programmer edit section *** (ОпрПотрТз.ТчОпрПотрТз Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОпрПотрТз.ТчОпрПотрТз Set start)

                // *** End programmer edit section *** (ОпрПотрТз.ТчОпрПотрТз Set start)
                this.fТчОпрПотрТз = value;
                // *** Start programmer edit section *** (ОпрПотрТз.ТчОпрПотрТз Set end)

                // *** End programmer edit section *** (ОпрПотрТз.ТчОпрПотрТз Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОпрПотрТзE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОпрПотрТзE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОпрПотрТзE", typeof(IIS.IB_Laboratornaya_Rabota.ОпрПотрТз));
                }
            }
            
            /// <summary>
            /// "ОпрПотрТзL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОпрПотрТзL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОпрПотрТзL", typeof(IIS.IB_Laboratornaya_Rabota.ОпрПотрТз));
                }
            }
        }
    }
}
