//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.IB_Laboratornaya_Rabota
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пр комп реш.
    /// </summary>
    // *** Start programmer edit section *** (ПрКомпРеш CustomAttributes)

    // *** End programmer edit section *** (ПрКомпРеш CustomAttributes)
    [AutoAltered()]
    [Caption("Пр комп реш")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПрКомпРешE", new string[] {
            "Дата as \'Дата создания\'",
            "ПериодПрОт as \'Период проектирования от\'",
            "ПериодПрДо as \'Период проектирования до\'",
            "СпрСотр as \'Ответственный\'",
            "СпрСотр.Фио as \'Ответственный\'"})]
    [AssociatedDetailViewAttribute("ПрКомпРешE", "ТЧПрКомпРеш", "ТЧПрКомпРешE", true, "", "Табличная часть проектирование комплексного решения", true, new string[] {
            ""})]
    [View("ПрКомпРешL", new string[] {
            "Дата as \'Дата создания\'",
            "ПериодПрОт as \'Период проектирования от\'",
            "ПериодПрДо as \'Период проектирования до\'",
            "СпрСотр.Фио as \'Ответственный\'"})]
    public class ПрКомпРеш : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private System.DateTime fПериодПрОт;
        
        private System.DateTime fПериодПрДо;
        
        private IIS.IB_Laboratornaya_Rabota.СпрСотр fСпрСотр;
        
        private IIS.IB_Laboratornaya_Rabota.DetailArrayOfТЧПрКомпРеш fТЧПрКомпРеш;
        
        // *** Start programmer edit section *** (ПрКомпРеш CustomMembers)

        // *** End programmer edit section *** (ПрКомпРеш CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ПрКомпРеш.Дата CustomAttributes)

        // *** End programmer edit section *** (ПрКомпРеш.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ПрКомпРеш.Дата Get start)

                // *** End programmer edit section *** (ПрКомпРеш.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ПрКомпРеш.Дата Get end)

                // *** End programmer edit section *** (ПрКомпРеш.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПрКомпРеш.Дата Set start)

                // *** End programmer edit section *** (ПрКомпРеш.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ПрКомпРеш.Дата Set end)

                // *** End programmer edit section *** (ПрКомпРеш.Дата Set end)
            }
        }
        
        /// <summary>
        /// ПериодПрДо.
        /// </summary>
        // *** Start programmer edit section *** (ПрКомпРеш.ПериодПрДо CustomAttributes)

        // *** End programmer edit section *** (ПрКомпРеш.ПериодПрДо CustomAttributes)
        public virtual System.DateTime ПериодПрДо
        {
            get
            {
                // *** Start programmer edit section *** (ПрКомпРеш.ПериодПрДо Get start)

                // *** End programmer edit section *** (ПрКомпРеш.ПериодПрДо Get start)
                System.DateTime result = this.fПериодПрДо;
                // *** Start programmer edit section *** (ПрКомпРеш.ПериодПрДо Get end)

                // *** End programmer edit section *** (ПрКомпРеш.ПериодПрДо Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПрКомпРеш.ПериодПрДо Set start)

                // *** End programmer edit section *** (ПрКомпРеш.ПериодПрДо Set start)
                this.fПериодПрДо = value;
                // *** Start programmer edit section *** (ПрКомпРеш.ПериодПрДо Set end)

                // *** End programmer edit section *** (ПрКомпРеш.ПериодПрДо Set end)
            }
        }
        
        /// <summary>
        /// ПериодПрОт.
        /// </summary>
        // *** Start programmer edit section *** (ПрКомпРеш.ПериодПрОт CustomAttributes)

        // *** End programmer edit section *** (ПрКомпРеш.ПериодПрОт CustomAttributes)
        public virtual System.DateTime ПериодПрОт
        {
            get
            {
                // *** Start programmer edit section *** (ПрКомпРеш.ПериодПрОт Get start)

                // *** End programmer edit section *** (ПрКомпРеш.ПериодПрОт Get start)
                System.DateTime result = this.fПериодПрОт;
                // *** Start programmer edit section *** (ПрКомпРеш.ПериодПрОт Get end)

                // *** End programmer edit section *** (ПрКомпРеш.ПериодПрОт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПрКомпРеш.ПериодПрОт Set start)

                // *** End programmer edit section *** (ПрКомпРеш.ПериодПрОт Set start)
                this.fПериодПрОт = value;
                // *** Start programmer edit section *** (ПрКомпРеш.ПериодПрОт Set end)

                // *** End programmer edit section *** (ПрКомпРеш.ПериодПрОт Set end)
            }
        }
        
        /// <summary>
        /// Пр комп реш.
        /// </summary>
        // *** Start programmer edit section *** (ПрКомпРеш.СпрСотр CustomAttributes)

        // *** End programmer edit section *** (ПрКомпРеш.СпрСотр CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрСотр"})]
        [NotNull()]
        public virtual IIS.IB_Laboratornaya_Rabota.СпрСотр СпрСотр
        {
            get
            {
                // *** Start programmer edit section *** (ПрКомпРеш.СпрСотр Get start)

                // *** End programmer edit section *** (ПрКомпРеш.СпрСотр Get start)
                IIS.IB_Laboratornaya_Rabota.СпрСотр result = this.fСпрСотр;
                // *** Start programmer edit section *** (ПрКомпРеш.СпрСотр Get end)

                // *** End programmer edit section *** (ПрКомпРеш.СпрСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПрКомпРеш.СпрСотр Set start)

                // *** End programmer edit section *** (ПрКомпРеш.СпрСотр Set start)
                this.fСпрСотр = value;
                // *** Start programmer edit section *** (ПрКомпРеш.СпрСотр Set end)

                // *** End programmer edit section *** (ПрКомпРеш.СпрСотр Set end)
            }
        }
        
        /// <summary>
        /// Пр комп реш.
        /// </summary>
        // *** Start programmer edit section *** (ПрКомпРеш.ТЧПрКомпРеш CustomAttributes)

        // *** End programmer edit section *** (ПрКомпРеш.ТЧПрКомпРеш CustomAttributes)
        public virtual IIS.IB_Laboratornaya_Rabota.DetailArrayOfТЧПрКомпРеш ТЧПрКомпРеш
        {
            get
            {
                // *** Start programmer edit section *** (ПрКомпРеш.ТЧПрКомпРеш Get start)

                // *** End programmer edit section *** (ПрКомпРеш.ТЧПрКомпРеш Get start)
                if ((this.fТЧПрКомпРеш == null))
                {
                    this.fТЧПрКомпРеш = new IIS.IB_Laboratornaya_Rabota.DetailArrayOfТЧПрКомпРеш(this);
                }
                IIS.IB_Laboratornaya_Rabota.DetailArrayOfТЧПрКомпРеш result = this.fТЧПрКомпРеш;
                // *** Start programmer edit section *** (ПрКомпРеш.ТЧПрКомпРеш Get end)

                // *** End programmer edit section *** (ПрКомпРеш.ТЧПрКомпРеш Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПрКомпРеш.ТЧПрКомпРеш Set start)

                // *** End programmer edit section *** (ПрКомпРеш.ТЧПрКомпРеш Set start)
                this.fТЧПрКомпРеш = value;
                // *** Start programmer edit section *** (ПрКомпРеш.ТЧПрКомпРеш Set end)

                // *** End programmer edit section *** (ПрКомпРеш.ТЧПрКомпРеш Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПрКомпРешE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПрКомпРешE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПрКомпРешE", typeof(IIS.IB_Laboratornaya_Rabota.ПрКомпРеш));
                }
            }
            
            /// <summary>
            /// "ПрКомпРешL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПрКомпРешL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПрКомпРешL", typeof(IIS.IB_Laboratornaya_Rabota.ПрКомпРеш));
                }
            }
        }
    }
}
