//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.IB_Laboratornaya_Rabota
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Раб отдел.
    /// </summary>
    // *** Start programmer edit section *** (РабОтдел CustomAttributes)

    // *** End programmer edit section *** (РабОтдел CustomAttributes)
    [AutoAltered()]
    [Caption("Раб отдел")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РабОтделE", new string[] {
            "Наименование as \'Рабочий отдел\'"})]
    [View("РабОтделL", new string[] {
            "Наименование as \'Рабочий отдел\'"})]
    public class РабОтдел : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (РабОтдел CustomMembers)

        // *** End programmer edit section *** (РабОтдел CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (РабОтдел.Наименование CustomAttributes)

        // *** End programmer edit section *** (РабОтдел.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (РабОтдел.Наименование Get start)

                // *** End programmer edit section *** (РабОтдел.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (РабОтдел.Наименование Get end)

                // *** End programmer edit section *** (РабОтдел.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РабОтдел.Наименование Set start)

                // *** End programmer edit section *** (РабОтдел.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (РабОтдел.Наименование Set end)

                // *** End programmer edit section *** (РабОтдел.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РабОтделE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РабОтделE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РабОтделE", typeof(IIS.IB_Laboratornaya_Rabota.РабОтдел));
                }
            }
            
            /// <summary>
            /// "РабОтделL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РабОтделL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РабОтделL", typeof(IIS.IB_Laboratornaya_Rabota.РабОтдел));
                }
            }
        }
    }
}
