//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.IB_Laboratornaya_Rabota
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тч опр потр тз.
    /// </summary>
    // *** Start programmer edit section *** (ТчОпрПотрТз CustomAttributes)

    // *** End programmer edit section *** (ТчОпрПотрТз CustomAttributes)
    [AutoAltered()]
    [Caption("Тч опр потр тз")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТчОпрПотрТзE", new string[] {
            "НаимТз as \'Наименование технической защиты\'",
            "ОпТз as \'Описание технической защиты\'"})]
    public class ТчОпрПотрТз : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаимТз;
        
        private string fОпТз;
        
        private IIS.IB_Laboratornaya_Rabota.ОпрПотрТз fОпрПотрТз;
        
        // *** Start programmer edit section *** (ТчОпрПотрТз CustomMembers)

        // *** End programmer edit section *** (ТчОпрПотрТз CustomMembers)

        
        /// <summary>
        /// НаимТз.
        /// </summary>
        // *** Start programmer edit section *** (ТчОпрПотрТз.НаимТз CustomAttributes)

        // *** End programmer edit section *** (ТчОпрПотрТз.НаимТз CustomAttributes)
        [StrLen(255)]
        public virtual string НаимТз
        {
            get
            {
                // *** Start programmer edit section *** (ТчОпрПотрТз.НаимТз Get start)

                // *** End programmer edit section *** (ТчОпрПотрТз.НаимТз Get start)
                string result = this.fНаимТз;
                // *** Start programmer edit section *** (ТчОпрПотрТз.НаимТз Get end)

                // *** End programmer edit section *** (ТчОпрПотрТз.НаимТз Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчОпрПотрТз.НаимТз Set start)

                // *** End programmer edit section *** (ТчОпрПотрТз.НаимТз Set start)
                this.fНаимТз = value;
                // *** Start programmer edit section *** (ТчОпрПотрТз.НаимТз Set end)

                // *** End programmer edit section *** (ТчОпрПотрТз.НаимТз Set end)
            }
        }
        
        /// <summary>
        /// ОпТз.
        /// </summary>
        // *** Start programmer edit section *** (ТчОпрПотрТз.ОпТз CustomAttributes)

        // *** End programmer edit section *** (ТчОпрПотрТз.ОпТз CustomAttributes)
        [StrLen(255)]
        public virtual string ОпТз
        {
            get
            {
                // *** Start programmer edit section *** (ТчОпрПотрТз.ОпТз Get start)

                // *** End programmer edit section *** (ТчОпрПотрТз.ОпТз Get start)
                string result = this.fОпТз;
                // *** Start programmer edit section *** (ТчОпрПотрТз.ОпТз Get end)

                // *** End programmer edit section *** (ТчОпрПотрТз.ОпТз Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчОпрПотрТз.ОпТз Set start)

                // *** End programmer edit section *** (ТчОпрПотрТз.ОпТз Set start)
                this.fОпТз = value;
                // *** Start programmer edit section *** (ТчОпрПотрТз.ОпТз Set end)

                // *** End programmer edit section *** (ТчОпрПотрТз.ОпТз Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.IB_Laboratornaya_Rabota.ОпрПотрТз.
        /// </summary>
        // *** Start programmer edit section *** (ТчОпрПотрТз.ОпрПотрТз CustomAttributes)

        // *** End programmer edit section *** (ТчОпрПотрТз.ОпрПотрТз CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ОпрПотрТз"})]
        public virtual IIS.IB_Laboratornaya_Rabota.ОпрПотрТз ОпрПотрТз
        {
            get
            {
                // *** Start programmer edit section *** (ТчОпрПотрТз.ОпрПотрТз Get start)

                // *** End programmer edit section *** (ТчОпрПотрТз.ОпрПотрТз Get start)
                IIS.IB_Laboratornaya_Rabota.ОпрПотрТз result = this.fОпрПотрТз;
                // *** Start programmer edit section *** (ТчОпрПотрТз.ОпрПотрТз Get end)

                // *** End programmer edit section *** (ТчОпрПотрТз.ОпрПотрТз Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчОпрПотрТз.ОпрПотрТз Set start)

                // *** End programmer edit section *** (ТчОпрПотрТз.ОпрПотрТз Set start)
                this.fОпрПотрТз = value;
                // *** Start programmer edit section *** (ТчОпрПотрТз.ОпрПотрТз Set end)

                // *** End programmer edit section *** (ТчОпрПотрТз.ОпрПотрТз Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТчОпрПотрТзE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТчОпрПотрТзE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТчОпрПотрТзE", typeof(IIS.IB_Laboratornaya_Rabota.ТчОпрПотрТз));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТчОпрПотрТз.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТчОпрПотрТз CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТчОпрПотрТз CustomAttributes)
    public class DetailArrayOfТчОпрПотрТз : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.IB_Laboratornaya_Rabota.DetailArrayOfТчОпрПотрТз members)

        // *** End programmer edit section *** (IIS.IB_Laboratornaya_Rabota.DetailArrayOfТчОпрПотрТз members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТчОпрПотрТз by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТчОпрПотрТз.
        /// </summary>
        public DetailArrayOfТчОпрПотрТз(IIS.IB_Laboratornaya_Rabota.ОпрПотрТз fОпрПотрТз) : 
                base(typeof(ТчОпрПотрТз), ((ICSSoft.STORMNET.DataObject)(fОпрПотрТз)))
        {
        }
        
        public IIS.IB_Laboratornaya_Rabota.ТчОпрПотрТз this[int index]
        {
            get
            {
                return ((IIS.IB_Laboratornaya_Rabota.ТчОпрПотрТз)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.IB_Laboratornaya_Rabota.ТчОпрПотрТз dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
