//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.IB_Laboratornaya_Rabota
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч пр комп реш.
    /// </summary>
    // *** Start programmer edit section *** (ТЧПрКомпРеш CustomAttributes)

    // *** End programmer edit section *** (ТЧПрКомпРеш CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч пр комп реш")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧПрКомпРешE", new string[] {
            "НазвМер as \'Название мероприятия\'",
            "ОписМер as \'Описание мероприятия\'"})]
    public class ТЧПрКомпРеш : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвМер;
        
        private string fОписМер;
        
        private IIS.IB_Laboratornaya_Rabota.ПрКомпРеш fПрКомпРеш;
        
        // *** Start programmer edit section *** (ТЧПрКомпРеш CustomMembers)

        // *** End programmer edit section *** (ТЧПрКомпРеш CustomMembers)

        
        /// <summary>
        /// НазвМер.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПрКомпРеш.НазвМер CustomAttributes)

        // *** End programmer edit section *** (ТЧПрКомпРеш.НазвМер CustomAttributes)
        [StrLen(255)]
        public virtual string НазвМер
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПрКомпРеш.НазвМер Get start)

                // *** End programmer edit section *** (ТЧПрКомпРеш.НазвМер Get start)
                string result = this.fНазвМер;
                // *** Start programmer edit section *** (ТЧПрКомпРеш.НазвМер Get end)

                // *** End programmer edit section *** (ТЧПрКомпРеш.НазвМер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПрКомпРеш.НазвМер Set start)

                // *** End programmer edit section *** (ТЧПрКомпРеш.НазвМер Set start)
                this.fНазвМер = value;
                // *** Start programmer edit section *** (ТЧПрКомпРеш.НазвМер Set end)

                // *** End programmer edit section *** (ТЧПрКомпРеш.НазвМер Set end)
            }
        }
        
        /// <summary>
        /// ОписМер.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПрКомпРеш.ОписМер CustomAttributes)

        // *** End programmer edit section *** (ТЧПрКомпРеш.ОписМер CustomAttributes)
        [StrLen(255)]
        public virtual string ОписМер
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПрКомпРеш.ОписМер Get start)

                // *** End programmer edit section *** (ТЧПрКомпРеш.ОписМер Get start)
                string result = this.fОписМер;
                // *** Start programmer edit section *** (ТЧПрКомпРеш.ОписМер Get end)

                // *** End programmer edit section *** (ТЧПрКомпРеш.ОписМер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПрКомпРеш.ОписМер Set start)

                // *** End programmer edit section *** (ТЧПрКомпРеш.ОписМер Set start)
                this.fОписМер = value;
                // *** Start programmer edit section *** (ТЧПрКомпРеш.ОписМер Set end)

                // *** End programmer edit section *** (ТЧПрКомпРеш.ОписМер Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.IB_Laboratornaya_Rabota.ПрКомпРеш.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПрКомпРеш.ПрКомпРеш CustomAttributes)

        // *** End programmer edit section *** (ТЧПрКомпРеш.ПрКомпРеш CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ПрКомпРеш"})]
        public virtual IIS.IB_Laboratornaya_Rabota.ПрКомпРеш ПрКомпРеш
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПрКомпРеш.ПрКомпРеш Get start)

                // *** End programmer edit section *** (ТЧПрКомпРеш.ПрКомпРеш Get start)
                IIS.IB_Laboratornaya_Rabota.ПрКомпРеш result = this.fПрКомпРеш;
                // *** Start programmer edit section *** (ТЧПрКомпРеш.ПрКомпРеш Get end)

                // *** End programmer edit section *** (ТЧПрКомпРеш.ПрКомпРеш Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПрКомпРеш.ПрКомпРеш Set start)

                // *** End programmer edit section *** (ТЧПрКомпРеш.ПрКомпРеш Set start)
                this.fПрКомпРеш = value;
                // *** Start programmer edit section *** (ТЧПрКомпРеш.ПрКомпРеш Set end)

                // *** End programmer edit section *** (ТЧПрКомпРеш.ПрКомпРеш Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧПрКомпРешE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧПрКомпРешE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧПрКомпРешE", typeof(IIS.IB_Laboratornaya_Rabota.ТЧПрКомпРеш));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧПрКомпРеш.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧПрКомпРеш CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧПрКомпРеш CustomAttributes)
    public class DetailArrayOfТЧПрКомпРеш : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.IB_Laboratornaya_Rabota.DetailArrayOfТЧПрКомпРеш members)

        // *** End programmer edit section *** (IIS.IB_Laboratornaya_Rabota.DetailArrayOfТЧПрКомпРеш members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧПрКомпРеш by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧПрКомпРеш.
        /// </summary>
        public DetailArrayOfТЧПрКомпРеш(IIS.IB_Laboratornaya_Rabota.ПрКомпРеш fПрКомпРеш) : 
                base(typeof(ТЧПрКомпРеш), ((ICSSoft.STORMNET.DataObject)(fПрКомпРеш)))
        {
        }
        
        public IIS.IB_Laboratornaya_Rabota.ТЧПрКомпРеш this[int index]
        {
            get
            {
                return ((IIS.IB_Laboratornaya_Rabota.ТЧПрКомпРеш)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.IB_Laboratornaya_Rabota.ТЧПрКомпРеш dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
